---
title: "Title: Cooling benefits and forest structure similar across parks with varied land use histories"
format: 
  html:
    toc: true
    html-math-method: katex
    self-contained-math: true
    self-contained: true
knitr:
  opts_knit:
    root.dir: "C:/Users/I_RICHMO/Documents/Repositories/park-legacies"
---

```{r, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
source('R/packages.R')
```

Authors: Isabella C. Richmond^1^\*, Michael A. Paulauskas^1^, Erica Padvaiskas^1^, Laura Carolina Gonzalez Sinisterra^2^, Kayleigh Hutt-Taylor^1^, Alec L. Robitaille^3^, Carly D. Ziter^1^

1 Department of Biology, Concordia University, Montreal Canada, H4B 1R6\
2 Department of Biology, Universidad del Valle, Cali Columbia, 760042 3 Department of Biology, Memorial University of Newfoundland, St John's Canada, A1C 5S7

\* isabella.richmond\@mail.concordia.ca, 438-439-8064

## Model Equations - Figure S4

Below are the math stats notations for all models run in our paper. 


## Total Effect of Past Land-Use on Cooling Effect


$$
Cooling_i \sim Normal(\mu_i, \sigma)
\\
\mu_i \sim \alpha_{Park[i]} + \alpha_{Plot[i]} + \gamma_{PLU[i]} + \gamma_{tod[i]} + \beta_{PLU}tod + \beta_{PLU[i]} + \beta_{tod[i]} + \beta_{age}age_i
\\
\alpha_{Park[j]} \sim Normal(\bar{\alpha}, \sigma_{\alpha_{Park}})
\\
\alpha_{Plot[j]} \sim Normal(0, \sigma_{\alpha_{Plot}})
\\
\gamma_j \sim Normal(0, 0.5)
\\
\beta_j \sim Normal(0, 0.5)
\\
\bar{\alpha} \sim Normal(0, 0.5)
\\
\sigma_{\alpha_{Park}} \sim Half-Normal(0, 0.2)
\\
\sigma_{\alpha_{Plot}} \sim Half-Normal(0, 0.2)
\\
\sigma \sim Exponential(1)
$$
-   $\alpha$ and $\gamma$ both represent intercepts, $\alpha$ is used for random effects and $\gamma$ for fixed interaction effecst 
-   $Cooling_i$ is the centered and scaled cooling effect in each plot in degrees Celsuis
-   $Park_i$ is the park that each plot is in 
-   $Plot_i$ is the plot that each measurement is in 
-   $PLU_i$ is the past land use category that each measurement is in (i.e., agricultural, forested, industrial)
-   $tod_i$ is the time of day category that each measurement is in (i.e., daytime, nighttime)
-   $age_i$ is the centered and scaled age of the park that each measurement is in 

## Direct Effect of Past Land-Use on Forest Composition

### Large Tree Density

$$
DensL_i \sim Normal(\mu_i, \sigma)
\\
\mu_i = \alpha + \beta_1forested_{[i]} + \beta_2industrial_{[i]}
\\
\alpha\sim Normal(0, 0.5)
\\
\beta_j \sim Normal(0, 0.5)
\\
\sigma \sim Exponential(1)
$$

Where:

-   $DensL_i$ is the centered and scaled basal area of large trees in each plot
-   `forested` is the factor level from `PastLandUse` that indicates previously forested parks. Previously agricultural parks are the default level, absorbed into the intercept. 
-   `industrial` is the factor level from `PastLandUse` that indicates previously forested parks. Previously agricultural parks are the default level, absorbed into the intercept.

### Small Tree Density

$$
log(DensS_i) \sim Normal(\mu_i, \sigma)
\\
\mu_i = \alpha + \beta_1forested_{[i]} + \beta_2industrial_{[i]}
\\
\alpha\sim Normal(0, 0.5)
\\
\beta_j \sim Normal(0, 0.5)
\\
\sigma \sim Exponential(1)
$$

-   $log(DensS_i)$ is the centered and scaled density of small trees in each plot. Logged for model fit.
-   `forested` is the factor level from `PastLandUse` that indicates previously forested parks. Previously agricultural parks are the default level, absorbed into the intercept. 
-   `industrial` is the factor level from `PastLandUse` that indicates previously forested parks. Previously agricultural parks are the default level, absorbed into the intercept.


### Large Tree Size

$$
SizeL_i \sim Normal(\mu_i, \sigma)
\\
\mu_i = \alpha + \beta_1forested_{[i]} + \beta_2industrial_{[i]}
\\
\alpha\sim Normal(-1, 0.5)
\\
\beta_j \sim Normal(0, 0.5)
\\
\sigma \sim Exponential(1)
$$

-   $SizeL_i$ is the centered and scaled median size of large trees in each plot.
-   `forested` is the factor level from `PastLandUse` that indicates previously forested parks. Previously agricultural parks are the default level, absorbed into the intercept. 
-   `industrial` is the factor level from `PastLandUse` that indicates previously forested parks. Previously agricultural parks are the default level, absorbed into the intercept.



### Small Tree Size

$$
SizeS_i \sim Normal(\mu_i, \sigma)
\\
\mu_i = \alpha + \beta_1forested_{[i]} + \beta_2industrial_{[i]}
\\
\alpha\sim Normal(1, 0.5)
\\
\beta_j \sim Normal(0, 0.5)
\\
\sigma \sim Exponential(1)
$$

-   $SizeS_i$ is the centered and scaled median size of small trees in each plot.
-   `forested` is the factor level from `PastLandUse` that indicates previously forested parks. Previously agricultural parks are the default level, absorbed into the intercept. 
-   `industrial` is the factor level from `PastLandUse` that indicates previously forested parks. Previously agricultural parks are the default level, absorbed into the intercept.


### Large Tree Species Richness

$$
SRL_i \sim Normal(\mu_i, \sigma)
\\
\mu_i = \alpha + \beta_1forested_{[i]} + \beta_2industrial_{[i]}
\\
\alpha\sim Normal(2, 1)
\\
\beta_j \sim Normal(0, 0.5)
\\
\sigma \sim Exponential(1)
$$

-   $SRL_i$ is the centered and scaled species richness of large trees in each plot.
-   `forested` is the factor level from `PastLandUse` that indicates previously forested parks. Previously agricultural parks are the default level, absorbed into the intercept. 
-   `industrial` is the factor level from `PastLandUse` that indicates previously forested parks. Previously agricultural parks are the default level, absorbed into the intercept.


## Direct Effect of Forest Composition on Cooling Effect

### Model equation

::: {style="overflow-x:auto;overflow-y:hidden;"}
$$
Cooling_i \sim Normal(\mu_i, \sigma)
\\
\mu_i \sim \alpha_{Park[i]} + \alpha_{Plot[i]} + \gamma_{tod[i]} + \beta_{tod[i]}DensityL_{i} + \beta_{tod[i]}DensityS_{i} + \beta_{tod[i]}SizeL_{i} + \beta_{tod[i]}SizeS_{i} + \beta_{tod[i]}SRL_{i} + \beta_{DensityL}DensityL_i + \beta_{DensityS}DensityS_i + \beta_{SizeL}SizeL_i + \beta_{SizeS}SizeS_i + \beta_{SRL}SRL_i 
\\
\alpha_{Park[j]} \sim Normal(\bar{\alpha}, \sigma_{\alpha_{Park}})
\\
\alpha_{Plot[j]} \sim Normal(0, \sigma_{\alpha_{Plot}})
\\
\gamma_j \sim Normal(0, 0.5)
\\
\beta_j \sim Normal(0, 0.5)
\\
\bar{\alpha} \sim Normal(0, 0.5)
\\
\sigma_{\alpha_{Park}} \sim Half-Normal(0, 0.2)
\\
\sigma_{\alpha_{Plot}} \sim Half-Normal(0, 0.2)
\\
\sigma \sim Exponential(1)
$$

:::
-   $\alpha$ and $\gamma$ both represent intercepts, $\alpha$ is used for random effects and $\gamma$ for fixed interaction effecst 
-   $Cooling_i$ is the centered and scaled cooling effect in each plot in degrees Celsuis
-   $Park_i$ is the park that each plot is in 
-   $Plot_i$ is the plot that each measurement is in 
-   $PLU_i$ is the past land use category that each measurement is in (i.e., agricultural, forested, industrial)
-   $tod_i$ is the time of day category that each measurement is in (i.e., daytime, nighttime)
-   $age_i$ is the centered and scaled age of the park that each measurement is in 